### ISSUE TITLE
Wow. Also license question.

### ISSUE THREAD

**Issue by sarahcrowle** [erichlof/THREE.js-PathTracing-Renderer#21]
First off, excuse my language, but this is badass. 

I was wondering, what license is this code under? maybe I missed something, but I was just wondering. Does it even have a license?

**Comment by erichlof** [comment]
@christiancrowle 
Hi Christian,
Thank you for the compliment!  Regarding licensing, no you didn't miss anything - I don't have any license for my code.  I've never been much about legal stuff.  However I AM all about the benefits of open source and sharing your knowledge.  If someone learns from this project, wonderful - if they want to grab some code and use it in their own project, that's great.   It would be nice if they credit the original author, whether it be me or someone else that I borrowed from.

Speaking of that, ray tracing has been around for a while and I can't really claim some of the classic algorithms and routines that I have used in the code-base.  When I have borrowed, I try to credit the author or where I got it from.  I guess my only claim is that I was able to gather disparate ray tracing sources around the internet and bring them together under the three.js umbrella and make real-time path tracing work in the browser and on mobile. 

I have been toying with the idea of making a YouTube video series (in the style of Handmade Hero) and explain step by step how I got this project going, but I don't know how Casey films all of that - something else to learn I guess!  ;-D
Thanks again,
-Erich

**Comment by sarahcrowle** [comment]
Thanks, good to know. I pretty much feel the same way about licensing. (not like I understand much of it anyway, haha). I do try to credit everyone I borrow from, just like I'd want them to do for me.

You really should do a video series! It's surprisingly hard to find nice, accessible information on raytracing. Lots of math, but I tend to learn better by walking through code and stuff. That's how I found your project.

Anyways, thanks for replying so quickly. Good luck on your future projects!
