### ISSUE TITLE
Some advise about WindowResize

### ISSUE THREAD

**Issue by RenderTool** [erichlof/THREE.js-PathTracing-Renderer#46]
Hello!thank you very much.
Now, I will give you some suggestions about screen adaptation on mobile app.
Wechat on the iPhone doesn't seem to support canvas very well. If you use window.innerheight and window.innerwidth control canvas size, the canvas height collapses when you rotate the phone screen. I changed to :    
     SCREEN_WIDTH = document.body.clientWidth;
     SCREEN_HEIGHT = document.body.clientHeight;
will back to normal.
![image](https://user-images.githubusercontent.com/31579609/74318519-63afac80-4db8-11ea-9b68-6a50fe417b9e.png)
![image](https://user-images.githubusercontent.com/31579609/74318600-8b9f1000-4db8-11ea-86f0-ba8f6148f3b3.png)

Threejs also has this problem.

**Comment by erichlof** [comment]
@q750831855 
Hello again!  Thank you for the suggestion!  I have taken your advice: [commit](https://github.com/erichlof/THREE.js-PathTracing-Renderer/commit/8aebcf0b8360aad93dd8d9008d214fbbe0b8ec26)

I also put in a credit to you in the updated source file. :-)

Thanks again,
-Erich
