### ISSUE TITLE
Launching issue

### ISSUE THREAD

**Issue by ghost** [erichlof/THREE.js-PathTracing-Renderer#5]
Hello.

I'm getting crashed everytime, never been in such trouble with any other WebGL content.

System specs:
OS: Microsoft Windows 7 Ultimate (64-bit)
CPU: Intel Core i7-6800K @ 4.2GHz
GPU: AMD Radeon HD6770 @ stock
RAM: 4x8GB DDR4 @ 2666 MHz
Browser: Chrome 59.0.3071.104 (64-bit)

Details on attached screenshot, thanks.

![2017-06-18_070753](https://user-images.githubusercontent.com/20195688/27258033-5cf2c80e-53f7-11e7-8a4a-52a2f7ead854.png)

**Comment by ghost** [comment]
With couple of refreshes and some magic I have get this working, but later it stuck with weird and ridiculously low fps. 

Can confirm that is such behavior is not renderer related, it's definitely caused by AMD Radeon Software Crimson Edition 16.2.1 Non WHQL Beta Driver, which is will be in beta forever because all non CGN videocards [are dropped](http://support.amd.com/en-us/download/desktop/legacy?product=legacy3&os=Windows+7+-+64) and now they're legacy products.

It's weird, because all other WebGL content is working the right way. But not so strange if remember what's happened when I installed latest Catalyst WHQL driver: it just doesn't have any support for WebGL at all.

![2017-06-18_081705](https://user-images.githubusercontent.com/20195688/27258353-0cbe2c5c-5401-11e7-944c-324f9b4e7ebf.png)

AMD drivers once again!

**Comment by erichlof** [comment]
@nxld 
Hi, sorry you are having graphics driver issues.  What year was your AMD Radeon made?  Is it an integrated card - PCI express slot?  

I try to make all the demos run on systems with basic specs.  I develop this repo using my i5/Windows 10 Toshiba laptop with humble integrated Intel graphics.  Most demos run at 45-60 fps on that. That last screenshot you posted was the Chrome software renderer.  If the shader keeps failing to compile for a certain number of times, it switches to software rendering at 0-1 fps.

I hope you are able to find the latest drivers for your card.  Let me know what you find and how it's going.

Thanks,
-Erich

**Comment by ghost** [comment]
@erichlof As I stated above, [Radeon HD6770](http://www.amd.com/en-us/products/graphics/desktop/6000/6770) is an DX11 PCI Express 2.1 x16 desktop videocard, released back in 2011. The problem is not about getting the latest drivers, both of their revisions (Crimson, actual AMD driver and Catalyst, older one) are outdated and dropped from development for legacy GPU's like my HD6770.  So it could produce some weird bugs and it does it :)

After I restarted the Chrome I got it crashed again and later when I just refreshed the page a few times I am getting nice 129 FPS (I have 144Hz display), who knows what it will be the next time.
![2017-06-18_100435](https://user-images.githubusercontent.com/20195688/27258867-4bf007d0-540e-11e7-9b88-c581b63786e6.png)

So I confirmed again, this is not an issue of your renderer and the drivers won't be fixed. 

Take this thread as a little research about "legacy videocards in modern WebGL environment".

Thanks for your project, I'll keep my eyes on it. You are great.

**Comment by erichlof** [comment]
Hi @nxld ,

Glad you were able to resolve the issue.  As I mentioned, I develop everything here on my humble laptop with integrated graphics, so I don't know a lot about WebGL support on graphics cards out in the wild.  One thing I will say though is, coming from my old days of OpenGL game programming in C on Windows 95/97, modern WebGL and Chrome/Firefox are wonderful to work with, knowing that most of what I see on my screen will end up on other people's screens as well! Even across mobile devices like my cellphone - something I couldn't have dreamed of back in 1997.

Thanks for the update and for watching my project.  Sorry there hasn't been updates recently:  I'm stuck on path tracing and lighting texture images from files, like .jpg's and .png's.  Hopefully I will 'crack the code' and post something soon. :)

Take care,
-Erich
