### ISSUE TITLE
Glitches in Constructive_Solid_Geometry_Viewer

### ISSUE THREAD

**Issue by mrdoob** [erichlof/THREE.js-PathTracing-Renderer#54]
https://erichlof.github.io/THREE.js-PathTracing-Renderer/Constructive_Solid_Geometry_Viewer.html

I remember these glitches being due to uninitialized variables.

Union:

<img width="1231" alt="Screen Shot 2021-03-10 at 10 36 25 AM" src="https://user-images.githubusercontent.com/97088/110616580-99c28a00-818c-11eb-9539-602821a55450.png">

Difference:

<img width="1231" alt="Screen Shot 2021-03-10 at 10 36 39 AM" src="https://user-images.githubusercontent.com/97088/110616606-a2b35b80-818c-11eb-8e61-c455d9382f6c.png">

Intersection:

<img width="1231" alt="Screen Shot 2021-03-10 at 10 36 53 AM" src="https://user-images.githubusercontent.com/97088/110616637-ac3cc380-818c-11eb-9b42-58d72e96bdbe.png">

Loving the progress! 😊

**Comment by jadsongmatos** [comment]
this yields a beautiful glitch effect

**Comment by erichlof** [comment]
@mrdoob 
Hello!  Thank you for the heads-up about this glitching issue.  If you don't mind, what system/GPU were the screenshots taken from?  I can't reproduce on my Toshiba Windows laptop with Intel integrated graphics, or my Windows Surface Laptop with GeForce GPU , or my Samsung S9 smartphone.  

In the meantime I'll take a look at my shader code for this demo and see if I forgot to initialize anything.  Thanks again!
-Erich

**Comment by mrdoob** [comment]
Chrome 89.0.4389.82
MacOS 10.15.7
MacBook Pro 2016
Intel Iris Graphics 550 1536 MB

**Comment by erichlof** [comment]
Ok thanks, unfortunately I don't have Apple devices like the MacBook that I can periodically test out my code on.  At any rate, just now I went back and initialized some of the float variables in the CSG viewer fragment shader.  Could you take another look and see if that helped at all?  Thanks - sorry for testing by proxy! :)

**Comment by mrdoob** [comment]
Unfortunately, seems like the issue is still there...

> Thanks - sorry for testing by proxy! :)

No worries!

**Comment by erichlof** [comment]
Ok thanks for checking.  I'll see if I can get access to an Apple device so I can debug more systematically.  Thanks again for the heads-up.
-Erich
