### ISSUE TITLE
More compatibility with three js APIs

### ISSUE THREAD

**Issue by vinkovsky** [erichlof/THREE.js-PathTracing-Renderer#65]
Hello Erich! Firstly, thanks for your work and for the advice you gave me. I have a question about your library's API. Do you plan to add abstractions in the future like what threejs uses to make it more similar?

**Comment by LeviPesin** [comment]
https://github.com/erichlof/THREE.js-PathTracing-Renderer/issues/62

**Comment by vinkovsky** [comment]
Hi @LeviPesin ! Thanks, I didn't see this.
